BBBB BBBBBB
BBBB BBBB
XXXX XXXXXXXXXXXX

XXXX
  XXXXXX XXXXXXXBB BBB BB BBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBXX gettext(u'Anasayfa') XXXXXXXXX
  XXXXXX XXXXXXXBB BBBBBBBBB BB BBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBBBXX gettext(u'Form Sayfası') XXXXXXXXX
  XXXXXX XXXXXXXBB BBBBBBBBBBBBBB BB BBBBBBBBBBBB XXXXXX BBBBBX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'Form Sorgula') XXXXXXXXX
XXXXX

XXXX XXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXBBBBBBBBBB
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXX
                    BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                    BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                    BBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBBB
                    BBB BBBBBBBB BB BBBBBBBBB
                        XXXXXXX XXXXXXXXBB BBBBBBBBBBBBB BB BBBBBBBBBBBBB XXXXXXXXBBBBBX
                             XX
                      XXXXXXXXX
                BBBBBB
                XXXXXXXXX
                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXXXXX
        XXXXX
    XXXXX
XXXXXX



XXXXXX







