# Generated by Django 3.2.5 on 2021-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('link', models.URLField(max_length=300)),
                ('aciklama', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
