# Generated by Django 3.2.5 on 2021-07-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
